### ISSUE TITLE
EISDIR while running aws-azure-login to login or configure profile

### ISSUE THREAD

**Issue by prerna1306** [kennethaasan/aws-azure-login#217]
While using aws-azure-login to either login using a profile or while configuring a profile, I was getting below error on windows - 

[Error: EISDIR: illegal operation on a directory, read] : {
errno: -4068,
code: 'EISDIR',
syscall: 'read'
}

Solution : In my windows environment variable, there was a environment variable named AWS_CONFIG_FILE which was pointing to {homeDir}/.aws i.e. to my aws folder and not to the config file inside aws folder. 
So when aws-azure-login tried to read the config file, the path used was that of a folder instead of file resulting in EISDIR. 
In the code, it first checks if there is  environment variable AWS_CONFIG_FILE  set. If yes, it uses it or constructs the path to config file. 
In my case, it used the AWS_CONFIG_FILE variable which was pointing to the folder instead of config file. 

SOLUTION is to remove the environment variable if not needed or edit it to point to the config file.

**Comment by jackson15j** [comment]
I had something similar on my intel mac but `AWS_CONFIG_FILE` was not set. I'm guessing a prior `brew install awscli` had created the empty folders of `~/.aws/config/` with the level of 755. This caused the following error:

```bash
% docker run --rm -it -v ~/.aws:/root/.aws sportradar/aws-azure-login --configure
Configuring profile 'default'
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```

Removing the `~/.aws/` folder has fixed this for me.
