### ISSUE TITLE
Microsoft Auth number matching

### ISSUE THREAD

**Issue by cdenneen** [kennethaasan/aws-azure-login#258]
Microsoft seems to be rolling out new auth method for number matching.
Currently unless I use gui mode I am not getting the number back in the CLI so can't provide a number and the app does not allow me to select alternative method.
![6124267e-3019-4ef5-b141-388b31b3eb25](https://user-images.githubusercontent.com/720097/205934502-02004f7a-4870-4a3a-a811-8894725f9103.jpg)
Is there anyway for the tool to scrape and provide back the number?

[aws-azure-login-debug.txt](https://github.com/aws-azure-login/aws-azure-login/files/10167435/aws-azure-login-debug.txt)

**Comment by cdenneen** [comment]
Screenshot from gui mode (example of number that needs to be scraped so it can be entered on the phone app)

![Screen Shot 2022-12-06 at 9 37 16 AM](https://user-images.githubusercontent.com/720097/205941310-b329016a-e9a2-456c-84ed-0e857bb449a5.png)

**Comment by MohamedAsan** [comment]
Hi @cdenneen, kindly check whether you are using the latest version(v3.5.1) of the package you have installed in which the issue is fixed(see [PR](https://github.com/aws-azure-login/aws-azure-login/pull/250))

**Comment by cdenneen** [comment]
@MohamedAsan that was it... was still running 3.4.0. Upgrade fixed it. Resolving issue. Thanks again.
