### ISSUE TITLE
Displaying authentication code does not work in other languages

### ISSUE THREAD

**Issue by Albert-IV** [kennethaasan/aws-azure-login#263]
[Looking at this commit, the logic for displaying the authentication code will not work on pages that use other languages.](https://github.com/aws-azure-login/aws-azure-login/commit/21574d056b935bc44a8f6585e443985679267a28)  We have devs working internationally using the tool, but once we required these authentication codes in Azure it breaks for our international colleagues.

Essentially there is german output saying that you need to enter the authentication code displayed and the console doesn't display the code.  If you run the application using the GUI mode, it is there on the page.

![Screenshot 2023-02-03 at 10 43 09 AM](https://user-images.githubusercontent.com/1487206/216658802-95e4d68f-72f7-42fd-83b5-776e474bdc82.png)

Attached is the HTML page of a German authentication page, if that helps.  I've tried to clear out as much identifying information as I can.

[german-2fa-response.html.txt](https://github.com/aws-azure-login/aws-azure-login/files/10580814/german-2fa-response.html.txt)

**Comment by Albert-IV** [comment]
I'm sorry for the lack of clear "when I do X, Y happens" sort of helpful details!  

We have a wrapper application that sits on top of `aws-azure-login` to store valid AWS accounts and provide some helpful CLI prompts and configuration that makes using the tool easier in our company's environment.  

Unfortunately that, along side the fact that I can't use the German pages personally makes it hard for me to give you the exact arguments that we're using for the tool.

**Comment by guerda** [comment]
What makes it hard for me is that I don't know where the German setting comes from. I'm one of the persons affected by that. 
I'm trying to change my OS to English to see if that changes the flow.

**Comment by MohamedAsan** [comment]
Published [v3.6.1](https://www.npmjs.com/package/aws-azure-login/v/3.6.1) which should fix the issue. Kindly let me know :)

Thanks to @guerda 🙏
