### ISSUE TITLE
AWS SDK v2 Deprecation

### ISSUE THREAD

**Issue by nathanloyer** [kennethaasan/aws-azure-login#268]
Hey all,

I recently updated to the latest version of aws-azure-login (3.6.1) and noticed when running it that there's a deprecation notice now in the CLI about AWS SDK for JavaScript (v2) going into maintenance mode.

```bash
> aws-azure-login
(node:23916) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
```

Are there already plans to update this package to the latest versions of the AWS SDK?

**Comment by gfrid** [comment]
any updates on this?

**Comment by gfrid** [comment]
Since older versions work how can we install older version until this is fixed?

**Comment by Glitchm** [comment]
Put a PR in for this: #275

Was able to authenticate no problem and no note pop up.

**Comment by gfrid** [comment]
> Put a PR in for this: #275
> 
> Was able to authenticate no problem and no note pop up.

10x

**Comment by aochsner** [comment]
> Put a PR in for this: #275
> 
> Was able to authenticate no problem and no note pop up.

Bit more involved than that...
see: #281

**Comment by Albert-IV** [comment]
Any update on enabling the tests for #281 and reviewing?

**Comment by nathanloyer** [comment]
Thanks for the fix @aochsner. Looks like this has been merged and the tags were updated, but I don't see the new version at npmjs.com yet. Is there a build that needs to be run to publish it?
