### ISSUE TITLE
Without chromium

### ISSUE THREAD

**Issue by mind-mind** [kennethaasan/aws-azure-login#297]
Hi,

Can I use aws-azure-login without Chromium in mac m2? 

My company is block chromium for some reason, but I still need to use aws azure to login.

**Comment by chatanooga** [comment]
I came across exactly the same issue and managed to fix by specifying chrome via an edit:
path to installation/lib/login.js
 browser = await puppeteer_1.default.launch({
                headless,
                **executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',**
                args,
                ignoreDefaultArgs,
            });

**Comment by zemacnica** [comment]
export PUPPETEER_EXECUTABLE_PATH='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' ; aws-azure-login --mode gui --profile default

**Comment by mind-mind** [comment]
> export PUPPETEER_EXECUTABLE_PATH='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'; aws-azure-login --mode gui --profile default

Thank you this problem already solve by this.
