### ISSUE TITLE
3.6.2 release

### ISSUE THREAD

**Issue by nathanloyer** [kennethaasan/aws-azure-login#309]
Hello,

I would like to start using the [change](https://github.com/aws-azure-login/aws-azure-login/pull/281) that resolved [this issue](https://github.com/aws-azure-login/aws-azure-login/issues/268), but it looks like the new package version has yet to be published to npmjs. 

```bash
> npm view aws-azure-login versions --registry https://registry.npmjs.com
[
  '0.0.1',  '0.0.2',  '0.1.0',  '0.1.1',  '0.2.0',
  '0.3.0',  '0.3.1',  '0.4.0',  '0.4.1',  '0.5.0',
  '0.6.0',  '0.6.1',  '0.6.2',  '0.6.3',  '1.0.0',
  '1.0.1',  '1.1.0',  '1.2.0',  '1.3.0',  '1.4.0',
  '1.4.1',  '1.5.0',  '1.5.1',  '1.6.0',  '1.7.0',
  '1.8.0',  '1.8.2',  '1.8.3',  '1.9.0',  '1.10.0',
  '1.11.0', '1.12.0', '1.13.0', '1.13.1', '1.13.2',
  '2.0.0',  '2.0.1',  '2.1.0',  '2.2.0',  '2.2.1',
  '2.2.2',  '2.2.3',  '2.2.4',  '2.2.5',  '2.2.6',
  '2.2.7',  '3.0.0',  '3.0.1',  '3.0.2',  '3.0.3',
  '3.1.0',  '3.2.0',  '3.2.1',  '3.2.2',  '3.3.0',
  '3.4.0',  '3.4.1',  '3.4.2',  '3.5.0',  '3.5.1',
  '3.6.0',  '3.6.1'
]
```

Could you push an official release for this or let us know when to expect it?

Thanks

**Comment by pjungermann** [comment]
seems like the release failed briefly after the version change was made:
https://github.com/aws-azure-login/aws-azure-login/actions/runs/5803904957

**Comment by tkofford** [comment]
I know this version only fixes a warning message, but is there an ETA of when this version will be successfully published?

Thanks in advance!

**Comment by ahester-incomm** [comment]
Bumping this thread, as #305 has been merged to main as well. @Naicigam28 Can we get a version release to npm please?

**Comment by robrich** [comment]
@Naicigam28 Need more maintainers?

**Comment by cjnoname** [comment]
@Naicigam28 Any chance to release this version? Because there're 6 critical vulnerabilities which required to be fixed asap.

**Comment by setrawicana** [comment]
Bumping this thread

**Comment by keanu-001** [comment]
@raybellwaves I had a look at the github action that is supposed to publish new versions. Seems it's been failing for a long time. Looks to be an authentication error. Can You confirm that the npm token used is still valid? At the moment I do not have access to that

**Comment by raybellwaves** [comment]
> @raybellwaves I had a look at the github action that is supposed to publish new versions. Seems it's been failing for a long time. Looks to be an authentication error. Can You confirm that the npm token used is still valid? At the moment I do not have access to that

I see https://github.com/aws-azure-login/aws-azure-login/actions/runs/7210168628/job/19642745664

 I never had access to https://www.npmjs.com/package/aws-azure-login. May have to try the owners there: 
  - https://www.npmjs.com/~cowboygneox (https://github.com/cowboygneox)
  - https://www.npmjs.com/~mohamedasan (https://github.com/MohamedAsan)

**Comment by keanu-001** [comment]
@kennethaasan @cowboygneox @MohamedAsan Would one of you be able to assist with this issue

**Comment by kennethaasan** [comment]
Hi, I'm no longer a maintainer or NPM owner of this library.

**Comment by keanu-001** [comment]
@nathanloyer Just release 3.6.3 on npm
