### ISSUE TITLE
login broken after cheerio 1.0.0 upgrade

### ISSUE THREAD

**Issue by sganslandt** [kennethaasan/aws-azure-login#339]
With a fresh install of `aws-azure-login` I'm getting `cheerio@1.0.0` installed. When trying to log in, I'm faced with the following error (together with the last line of debug output). 
```
  aws-azure-login Parsing SAML XML +0ms
TypeError: Cannot read properties of undefined (reading 'load')
    at Object._parseRolesFromSamlResponse (/opt/homebrew/lib/node_modules/aws-azure-login/lib/login.js:663:40)
    at Object.loginAsync (/opt/homebrew/lib/node_modules/aws-azure-login/lib/login.js:379:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
``` 

Downgrading to `cheerio@1.0.0-rc.12` fixes the issues.

**Comment by srinivasan-sains** [comment]
kindly help with command to downgrade cheerio@1.0.0-rc.12 from mac terminal

**Comment by srinivasan-sains** [comment]
it is not fixing to me even after downgrading and even i tried removing it.

> Please complete the login in the opened window
> TypeError: Cannot read properties of undefined (reading 'load')
>     at Object._parseRolesFromSamlResponse (/Users/<firstname.lastname>/.npm-global/lib/node_modules/aws-azure-login/lib/login.js:663:40)
>     at Object.loginAsync (/Users/<firstname.lastname>/.npm-global/lib/node_modules/aws-azure-login/lib/login.js:379:28)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I noticed that it is not generating credentials file under /.aws/

**Comment by oliverjfletcher** [comment]
Same issue for me as well. Also tried to install v3.6.0 and same issue.

```
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
TypeError: Cannot read properties of undefined (reading 'load')
    at Object._parseRolesFromSamlResponse (/opt/homebrew/lib/node_modules/aws-azure-login/lib/login.js:663:40)
    at Object.loginAsync (/opt/homebrew/lib/node_modules/aws-azure-login/lib/login.js:379:28)
```

**Comment by josephwccheng** [comment]
Also facing the same issue:
TypeError: Cannot read properties of undefined (reading 'load')
    at Object._parseRolesFromSamlResponse (/opt/homebrew/lib/node_modules/aws-azure-login/lib/login.js:663:40)
    at Object.loginAsync (/opt/homebrew/lib/node_modules/aws-azure-login/lib/login.js:379:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by sganslandt** [comment]
>Same issue for me as well. Also tried to install v3.6.0 and same issue.

I guess the problem is that the cheerio dependency is defined as the given version or higher, and currently 1.0.0 is the latest.  

Changing [this](https://github.com/aws-azure-login/aws-azure-login/blob/main/package.json#L35) to `"1.0.0-rc.12"` (exact version) and running `npm install` inside the module folder is how I made it work. Needed to be run with an older version of Node (18.18.1) for some reason.

**Comment by oliverjfletcher** [comment]
Thanks @sganslandt, I tried updating my [pnpm package.json](https://pnpm.io/package_json#pnpmoverrides) to the below and still I am seeing the same error after uninstalling the re-installing aws-azure-login with `pnpm uninstall aws-azure-login` then `pnpm install aws-azure-login` Forgive me, I am a noob when it comes to JS package management.

```json
{
	"pnpm": {
		"overrides": {
			"cheerio": "1.0.0-rc.10",
			"cheerio-select": "2.0.0"
		}
	},
	"dependencies": {
		"aws-azure-login": "^3.6.3"
	}
}
```

**Comment by gintalk** [comment]
This is what worked for me @oliverjfletcher:

1. Go to your global npm `node_modules` folder (for my Mac it is `/usr/local/lib/node_modules`)
2. You should see a folder named `aws-azure-login`, go to that folder
3. Edit the `package.json` file found inside the above folder
4. Under `dependencies` you should see an entry for `cheerio`, change it to `1.0.0-rc.12`
5. Save
6. Open a terminal inside that same folder and run `npm install` (sometimes you need `sudo`)

After it finishes it should work. I haven't used `pnpm` but I guess it works the same way as `npm`.
Hope that helps.

**Comment by rohancragg** [comment]
Due to lack of TypeScript and JavaScript proficiency I'm unable to fix this myself but I do note that line 892 of `login.ts` is calling `cherio.load()`, and I wonder if this indicates the source of the problem?:

https://cheerio.js.org/docs/api/interfaces/CheerioAPI#load is marked as deprecated with the message:

> The .load static method defined on the "loaded" Cheerio factory function is deprecated. Users are encouraged to instead use the load function exported by the Cheerio module.

**Comment by josephwccheng** [comment]
@gintalk  this worked for me too :)

**Comment by josephwccheng** [comment]
Note: @gintalk your step worked.
I downloaded npm via homebrew, so the directory for the global npm folder is:
/opt/homebrew/lib/node_modules

**Comment by mark-r-m** [comment]
> > Same issue for me as well. Also tried to install v3.6.0 and same issue.
> 
> I guess the problem is that the cheerio dependency is defined as the given version or higher, and currently 1.0.0 is the latest.
> 
> Changing [this](https://github.com/aws-azure-login/aws-azure-login/blob/main/package.json#L35) to `"1.0.0-rc.12"` (exact version) and running `npm install` inside the module folder is how I made it work. Needed to be run with an older version of Node (18.18.1) for some reason.

Same for us today. Put Node down to v18, set dependency to exactly `"1.0.0-rc.12"`, running `npm install` in there, fixed it up.

Incidentally, we also set 

```sh
export PUPPETEER_EXECUTABLE_PATH='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
```

in our `~/.zshrc`, but I don't think that was directly related, more for environmental constraints we have.

**Comment by Vasanthagokul** [comment]
Hi Everyone, i saw that PR 340 had updates to the code base as well.  A simple update to the package.json will fix this issue and hence I opened a PR for it #341  . Please do leave some comments on it as it's my first ever PR that I've created!

**Comment by Garethp** [comment]
While this waits for the maintainer to resolve it, I've forked `aws-azure-login` into [`aws-azure-auth`](https://github.com/Garethp/aws-azure-auth). It's published into npm at the moment and over the weekend I'll take a look into putting it onto Docker and perhaps snapcraft if I can. I'll also be looking into bringing in some of the open issues/improvements on this project.

On top of that, I'm hoping to fold in a CDK plugin into that package as well so that it can automatically detect and refresh credentials for an environment that you wish to deploy into

**Comment by kitconnickedf** [comment]
Hi all, I followed all the steps here but am still facing the same issue?

**Comment by Garethp** [comment]
> Hi all, I followed all the steps here but am still facing the same issue? 

If you're having trouble manually patching it, I'd suggest uninstalling `aws-azure-login` and installing `aws-azure-auth` instead with `npm i -g aws-azure-auth`

**Comment by kitconnickedf** [comment]
@Garethp thank you very much I'll try that now

**Comment by Pratikshakilledar** [comment]
I am using windows cmd and getting same issue, please help me.

**Comment by Garethp** [comment]
@Pratikshakilledar, try using and installing [`aws-azure-auth`](https://www.npmjs.com/package/aws-azure-auth) as a replacement instead.

@sganslandt, can I suggest editing your first message in the issue to point to my fork since the maintainer of `aws-azure-login` isn't responding and people don't tend to always read the comment chain on issues

**Comment by Pratikshakilledar** [comment]
Other commands are like azure-azure-login etc. I am want to setup AWS profiles, will it work?

**Comment by Pratikshakilledar** [comment]
> This is what worked for me @oliverjfletcher:
> 
> 1. Go to your global npm `node_modules` folder (for my Mac it is `/usr/local/lib/node_modules`)
> 2. You should see a folder named `aws-azure-login`, go to that folder
> 3. Edit the `package.json` file found inside the above folder
> 4. Under `dependencies` you should see an entry for `cheerio`, change it to `1.0.0-rc.12`
> 5. Save
> 6. Open a terminal inside that same folder and run `npm install` (sometimes you need `sudo`)
> 
> After it finishes it should work. I haven't used `pnpm` but I guess it works the same way as `npm`. Hope that helps.

I have followed steps but still getting same error

**Comment by INRIX-Christopher-Storer** [comment]
> While this waits for the maintainer to resolve it, I've forked `aws-azure-login` into [`aws-azure-auth`](https://github.com/Garethp/aws-azure-auth). It's published into npm at the moment and over the weekend I'll take a look into putting it onto Docker and perhaps snapcraft if I can. I'll also be looking into bringing in some of the open issues/improvements on this project.
> 
> On top of that, I'm hoping to fold in a CDK plugin into that package as well so that it can automatically detect and refresh credentials for an environment that you wish to deploy into

You are a lovely person.  I switched to this and now everything is working perfectly while we wait!

**Comment by arindam-giri** [comment]
> While this waits for the maintainer to resolve it, I've forked `aws-azure-login` into [`aws-azure-auth`](https://github.com/Garethp/aws-azure-auth). It's published into npm at the moment and over the weekend I'll take a look into putting it onto Docker and perhaps snapcraft if I can. I'll also be looking into bringing in some of the open issues/improvements on this project.
> 
> On top of that, I'm hoping to fold in a CDK plugin into that package as well so that it can automatically detect and refresh credentials for an environment that you wish to deploy into

This one worked only. Thanks @Garethp

**Comment by HarshalHarawat2897** [comment]
I have tried all the above steps but didn't work for me
Facing below error:
TypeError: Cannot read properties of undefined (reading 'load')                                                                                                                                  at Object._parseRolesFromSamlResponse (C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:662:40)  at Object.loginAsync (C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:378:28)  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by sganslandt** [comment]
After a re-install of 3.6.3 I'm still facing the same issue, with the same error. Downgrading cheerio still fixes the issue. Is it only me, and am I missing something in the re-install process?

**Comment by rohancragg** [comment]
> After a re-install of 3.6.3 I'm still facing the same issue, with the same error. Downgrading cheerio still fixes the issue. Is it only me, and am I missing something in the re-install process?

You need to be using v.3.6.4 which you can get from NPM: https://www.npmjs.com/package/aws-azure-login but it raises the important question how on earth 3.6.3 is still the latest release here on GitHub?!

**Comment by sganslandt** [comment]
🤦 thanks! I blindly took the latest version form Github and didn't notice it was the same.
